In [2]:
## Table of Contents
1. [Data Loading](#data-loading)
2. [Data Exploration](#data-exploration)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1380934815.py, line 2)

# Data Loading

In [1]:
#packages 
from pathlib import Path
import pandas as pd

In [12]:
# paths 
project_fldr = Path.cwd().parent
raw_fldr = project_fldr /'Data'/'unprocessed' 
processed_fldr = project_fldr /'Data'/'processed'

In [17]:
# Importing the dataframe 
EPA_Metals = (
    pd.read_csv(
        raw_fldr/'TerrestrialReport.csv')
)
epest = pd.read_csv("https://www.sciencebase.gov/catalog/file/get/5e95c12282ce172707f2524e?name=EPest_county_estimates_2013_2017_v2.txt", sep="\t")
matching =  (
    pd.read_csv(
        raw_fldr/'epest_compounds_cas.csv')
)

In [15]:
EPA_Metals.head()

,CAS Number,Chemical Name,Chemical Grade,Chemical Analysis Method,Chemical Purity Mean Op,Chemical Purity Mean(%),Chemical Purity Min Op,Chemical Purity Min(%),Chemical Purity Max Op,Chemical Purity Max(%),...,Observed Duration Min (Days),Observed Duration Max Op (Days),Observed Duration Max (Days),Observed Duration Units (Days),Author,Reference Number,Title,Source,Publication Year,Citation
0,50293,"1,1'-(2,2,2-Trichloroethylidene)bis[4-chlorobe...","Technical grade, technical product, technical ...",Measured,NaN,NR,NaN,NR,NaN,NR,...,6,NaN,122,Day(s),"Bandy,L.W.",47287,The Bioaccumulation and Translocation of Ring-...,"Ph.D. Thesis, The Ohio State University, Colum...",1972,"Bandy,L.W. (1972). The Bioaccumulation and Tra..."
1,50293,"1,1'-(2,2,2-Trichloroethylidene)bis[4-chlorobe...",Not reported,Unmeasured,NaN,90,NaN,NR,NaN,NR,...,NR,NaN,NR,Day(s),"Devi,K.I., S. Paul, S.H. Devi, and S. Giri",160427,Effect of Chlorpyriphos and Dichlorodiphenyl -...,J. Ecotoxicol. Environ. Monit.19(2): 135-142,2009,"Devi,K.I., S. Paul, S.H. Devi, and S. Giri (20..."
2,50293,"1,1'-(2,2,2-Trichloroethylidene)bis[4-chlorobe...",Not reported,Unmeasured,NaN,90,NaN,NR,NaN,NR,...,NR,NaN,NR,Day(s),"Devi,K.I., S. Paul, S.H. Devi, and S. Giri",160427,Effect of Chlorpyriphos and Dichlorodiphenyl -...,J. Ecotoxicol. Environ. Monit.19(2): 135-142,2009,"Devi,K.I., S. Paul, S.H. Devi, and S. Giri (20..."
3,50293,"1,1'-(2,2,2-Trichloroethylidene)bis[4-chlorobe...",Not reported,Unmeasured,NaN,5,NaN,NR,NaN,NR,...,NR,NaN,NR,Harvest,"Banham,F.L.",42529,The Effect of Certain Insecticides on the Germ...,Proc. Entomol. Soc. B. C.48:67-69,1951,"Banham,F.L. (1951). The Effect of Certain Inse..."
4,50293,"1,1'-(2,2,2-Trichloroethylidene)bis[4-chlorobe...",Not reported,Unmeasured,NaN,5,NaN,NR,NaN,NR,...,NR,NaN,NR,Harvest,"Banham,F.L.",42529,The Effect of Certain Insecticides on the Germ...,Proc. Entomol. Soc. B. C.48:67-69,1951,"Banham,F.L. (1951). The Effect of Certain Inse..."

In [16]:
epest.head()

,COMPOUND,YEAR,STATE_FIPS_CODE,COUNTY_FIPS_CODE,EPEST_LOW_KG,EPEST_HIGH_KG
0,1-METHYL CYCLOPROPENE,2013,41,1,NaN,0.0
1,1-METHYL CYCLOPROPENE,2013,41,21,NaN,0.0
2,1-METHYL CYCLOPROPENE,2013,41,27,NaN,0.2
3,1-METHYL CYCLOPROPENE,2013,41,49,NaN,0.0
4,1-METHYL CYCLOPROPENE,2013,41,55,NaN,0.0

In [18]:
matching.head()

                COMPOUND       CASRN  CAS Number
0  1-METHYL CYCLOPROPENE   3100-04-7   3100047.0
1                  2,4-D     94-75-7     94757.0
2                 2,4-DB     94-82-6     94826.0
3        6-BENZYLADENINE   1214-39-7   1214397.0
4              ABAMECTIN  71751-41-2  71751412.0

## Data Exploration