## Table of Contents
1. [Data Loading](#data-loading)
2. [Data Exploration](#data-exploration)
3. [Data Cleaning](#data-cleaning)

# Data Loading

In [2]:
#packages 
from pathlib import Path
import pandas as pd

In [3]:
# paths 
project_fldr = Path.cwd().parent
raw_fldr = project_fldr /'Data'/'unprocessed' 
processed_fldr = project_fldr /'Data'/'processed'

In [11]:
# Importing the dataframe 
EPA_Dataset = (
    pd.read_csv(
        raw_fldr/'TerrestrialReport.csv')
)
epest = pd.read_csv("https://www.sciencebase.gov/catalog/file/get/5e95c12282ce172707f2524e?name=EPest_county_estimates_2013_2017_v2.txt", sep="\t")
matching =  (
    pd.read_csv(
        raw_fldr/'epest_compounds_cas.csv')
)

# Data Exploration

In [12]:
EPA_Dataset.head()

,CAS Number,Chemical Name,Chemical Grade,Chemical Analysis Method,Chemical Purity Mean Op,Chemical Purity Mean(%),Chemical Purity Min Op,Chemical Purity Min(%),Chemical Purity Max Op,Chemical Purity Max(%),...,Observed Duration Min (Days),Observed Duration Max Op (Days),Observed Duration Max (Days),Observed Duration Units (Days),Author,Reference Number,Title,Source,Publication Year,Citation
0,50293,"1,1'-(2,2,2-Trichloroethylidene)bis[4-chlorobe...","Technical grade, technical product, technical ...",Measured,NaN,NR,NaN,NR,NaN,NR,...,6,NaN,122,Day(s),"Bandy,L.W.",47287,The Bioaccumulation and Translocation of Ring-...,"Ph.D. Thesis, The Ohio State University, Colum...",1972,"Bandy,L.W. (1972). The Bioaccumulation and Tra..."
1,50293,"1,1'-(2,2,2-Trichloroethylidene)bis[4-chlorobe...",Not reported,Unmeasured,NaN,90,NaN,NR,NaN,NR,...,NR,NaN,NR,Day(s),"Devi,K.I., S. Paul, S.H. Devi, and S. Giri",160427,Effect of Chlorpyriphos and Dichlorodiphenyl -...,J. Ecotoxicol. Environ. Monit.19(2): 135-142,2009,"Devi,K.I., S. Paul, S.H. Devi, and S. Giri (20..."
2,50293,"1,1'-(2,2,2-Trichloroethylidene)bis[4-chlorobe...",Not reported,Unmeasured,NaN,90,NaN,NR,NaN,NR,...,NR,NaN,NR,Day(s),"Devi,K.I., S. Paul, S.H. Devi, and S. Giri",160427,Effect of Chlorpyriphos and Dichlorodiphenyl -...,J. Ecotoxicol. Environ. Monit.19(2): 135-142,2009,"Devi,K.I., S. Paul, S.H. Devi, and S. Giri (20..."
3,50293,"1,1'-(2,2,2-Trichloroethylidene)bis[4-chlorobe...",Not reported,Unmeasured,NaN,5,NaN,NR,NaN,NR,...,NR,NaN,NR,Harvest,"Banham,F.L.",42529,The Effect of Certain Insecticides on the Germ...,Proc. Entomol. Soc. B. C.48:67-69,1951,"Banham,F.L. (1951). The Effect of Certain Inse..."
4,50293,"1,1'-(2,2,2-Trichloroethylidene)bis[4-chlorobe...",Not reported,Unmeasured,NaN,5,NaN,NR,NaN,NR,...,NR,NaN,NR,Harvest,"Banham,F.L.",42529,The Effect of Certain Insecticides on the Germ...,Proc. Entomol. Soc. B. C.48:67-69,1951,"Banham,F.L. (1951). The Effect of Certain Inse..."

In [13]:
epest.head()

,COMPOUND,YEAR,STATE_FIPS_CODE,COUNTY_FIPS_CODE,EPEST_LOW_KG,EPEST_HIGH_KG
0,1-METHYL CYCLOPROPENE,2013,41,1,NaN,0.0
1,1-METHYL CYCLOPROPENE,2013,41,21,NaN,0.0
2,1-METHYL CYCLOPROPENE,2013,41,27,NaN,0.2
3,1-METHYL CYCLOPROPENE,2013,41,49,NaN,0.0
4,1-METHYL CYCLOPROPENE,2013,41,55,NaN,0.0

In [14]:
matching.head()

                COMPOUND       CASRN  CAS Number
0  1-METHYL CYCLOPROPENE   3100-04-7   3100047.0
1                  2,4-D     94-75-7     94757.0
2                 2,4-DB     94-82-6     94826.0
3        6-BENZYLADENINE   1214-39-7   1214397.0
4              ABAMECTIN  71751-41-2  71751412.0

In [15]:
EPA_Dataset.shape

(6147, 75)

In [16]:
epest.shape

(2004805, 6)

In [17]:
matching.shape

(448, 3)

In [18]:
EPA_Dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 6147 entries, 0 to 6146
Data columns (total 75 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   CAS Number                       6147 non-null   int64
 1   Chemical Name                    6147 non-null   str
 2   Chemical Grade                   6147 non-null   str
 3   Chemical Analysis Method         6147 non-null   str
 4   Chemical Purity Mean Op          8 non-null      str
 5   Chemical Purity Mean(%)          6147 non-null   str
 6   Chemical Purity Min Op           0 non-null      float64
 7   Chemical Purity Min(%)           6147 non-null   str
 8   Chemical Purity Max Op           0 non-null      float64
 9   Chemical Purity Max(%)           6147 non-null   str
 10  Species Scientific Name          6147 non-null   str
 11  Species Common Name              6147 non-null   str
 12  Species Group                    6147 non-null   str
 13  Organism Lifestage               6147 non-null   str
 14  Organism Age Mean Op             21 non-null     str
 15  Organism Age Mean                6147 non-null   str
 16  Organism Age Min Op              0 non-null      float64
 17  Organism Age Min                 6147 non-null   str
 18  Organism Age Max Op              0 non-null      float64
 19  Organism Age Max                 6147 non-null   str
 20  Organism Age Units               6147 non-null   str
 21  Exposure Type                    6147 non-null   str
 22  Media Type                       6147 non-null   str
 23  Test Location                    6147 non-null   str
 24  Number of Doses                  6147 non-null   str
 25  Conc 1 Type (Author)             6141 non-null   str
 26  Conc 1 Mean Op (Author)          192 non-null    str
 27  Conc 1 Mean (Author)             6141 non-null   str
 28  Conc 1 Min Op (Author)           106 non-null    str
 29  Conc Min 1 (Author)              6141 non-null   str
 30  Conc 1 Max Op (Author)           105 non-null    str
 31  Conc 1 Max (Author)              6141 non-null   str
 32  Conc 1 Units (Author)            6141 non-null   str
 33  Conc 2 Type (Author)             3 non-null      str
 34  Conc 2 Mean Op (Author)          0 non-null      float64
 35  Conc 2 Mean (Author)             3 non-null      float64
 36  Conc 2 Min Op (Author)           0 non-null      float64
 37  Conc Min 2 (Author)              3 non-null      str
 38  Conc 2 Max Op (Author)           0 non-null      float64
 39  Conc 2 Max (Author)              3 non-null      str
 40  Conc 2 Units (Author)            3 non-null      str
 41  Conc 3 Type (Author)             0 non-null      float64
 42  Conc 3 Mean Op (Author)          0 non-null      float64
 43  Conc 3 Mean (Author)             0 non-null      float64
 44  Conc 3 Min Op (Author)           0 non-null      float64
 45  Conc Min 3 (Author)              0 non-null      float64
 46  Conc 3 Max Op (Author)           0 non-null      float64
 47  Conc 3 Max (Author)              0 non-null      float64
 48  Conc 3 Units (Author)            0 non-null      float64
 49  Effect                           6147 non-null   str
 50  Effect Measurement               6147 non-null   str
 51  Endpoint                         6147 non-null   str
 52  Observed Response Mean Op        216 non-null    str
 53  Observed Response Mean           6141 non-null   str
 54  Observed Response Min Op         232 non-null    str
 55  Observed Response Min            6141 non-null   str
 56  Observed Response Max Op         230 non-null    str
 57  Observed Response Max            6141 non-null   str
 58  Result Statistical Method        0 non-null      float64
 59  Observed Response Value          0 non-null      float64
 60  Observed Response Units          6141 non-null   str
 61  Response Site                    6147 non-null   str
 62  Observed Duration Op (Days)      461 non-null    str
 63  Observed Duration (Days)         6147 non-null   str
 64  Observed Duration Min Op (Days)  9 non-null      str
 65  Observed Duration Min (Days)     6147 non-null   str
 66  Observed Duration Max Op (Days)  9 non-null      str
 67  Observed Duration Max (Days)     6147 non-null   str
 68  Observed Duration Units (Days)   6147 non-null   str
 69  Author                           6147 non-null   str
 70  Reference Number                 6147 non-null   int64
 71  Title                            6147 non-null   str
 72  Source                           6147 non-null   str
 73  Publication Year                 6147 non-null   int64
 74  Citation                         6147 non-null   str
dtypes: float64(18), int64(3), str(54)
memory usage: 3.5 MB

In [19]:
epest.info()

<class 'pandas.DataFrame'>
RangeIndex: 2004805 entries, 0 to 2004804
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   COMPOUND          str
 1   YEAR              int64
 2   STATE_FIPS_CODE   int64
 3   COUNTY_FIPS_CODE  int64
 4   EPEST_LOW_KG      float64
 5   EPEST_HIGH_KG     float64
dtypes: float64(2), int64(3), str(1)
memory usage: 91.8 MB

In [20]:
matching.info()

<class 'pandas.DataFrame'>
RangeIndex: 448 entries, 0 to 447
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   COMPOUND    448 non-null    str
 1   CASRN       409 non-null    str
 2   CAS Number  409 non-null    float64
dtypes: float64(1), str(2)
memory usage: 10.6 KB

In [21]:
EPA_Dataset.describe()

,CAS Number,Chemical Purity Min Op,Chemical Purity Max Op,Organism Age Min Op,Organism Age Max Op,Conc 2 Mean Op (Author),Conc 2 Mean (Author),Conc 2 Min Op (Author),Conc 2 Max Op (Author),Conc 3 Type (Author),...,Conc 3 Mean (Author),Conc 3 Min Op (Author),Conc Min 3 (Author),Conc 3 Max Op (Author),Conc 3 Max (Author),Conc 3 Units (Author),Result Statistical Method,Observed Response Value,Reference Number,Publication Year
count,6.147000e+03,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6147.000000,6147.000000
mean,1.533282e+08,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141799.587441,2007.453717
std,8.266289e+07,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49259.735819,10.238735
min,5.029300e+04,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,344.000000,1948.000000
25%,1.318603e+08,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105672.000000,2004.000000
50%,1.382614e+08,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162940.000000,2009.000000
75%,1.537192e+08,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183585.000000,2014.000000
max,9.094040e+08,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193031.000000,2022.000000

In [22]:
epest.describe()

,YEAR,STATE_FIPS_CODE,COUNTY_FIPS_CODE,EPEST_LOW_KG,EPEST_HIGH_KG
count,2.004805e+06,2.004805e+06,2.004805e+06,1.363143e+06,2.004805e+06
mean,2.014925e+03,3.062408e+01,9.553804e+01,1.702369e+03,1.327162e+03
std,1.413883e+00,1.484951e+01,8.628876e+01,2.200232e+04,1.854794e+04
min,2.013000e+03,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00
25%,2.014000e+03,1.800000e+01,3.500000e+01,1.200000e+00,1.800000e+00
50%,2.015000e+03,2.900000e+01,7.700000e+01,1.420000e+01,1.800000e+01
75%,2.016000e+03,4.500000e+01,1.310000e+02,1.506000e+02,1.491000e+02
max,2.017000e+03,5.600000e+01,8.100000e+02,5.569201e+06,5.569201e+06

In [24]:
matching.describe()

         CAS Number
count  4.090000e+02
mean   9.558888e+07
std    1.697108e+08
min    5.103600e+04
25%    1.918021e+06
50%    5.133827e+07
75%    1.177186e+08
max    1.072958e+09

In [25]:
missing_percent = EPA_Dataset.isna().mean().sort_values(ascending=False) * 100
missing_percent

Chemical Purity Min Op     100.0
Chemical Purity Max Op     100.0
Observed Response Value    100.0
Conc 3 Mean (Author)       100.0
Conc 2 Mean Op (Author)    100.0
                           ...
Reference Number             0.0
Title                        0.0
Source                       0.0
Publication Year             0.0
Citation                     0.0
Length: 75, dtype: float64

In [26]:
missing_percent = epest.isna().mean().sort_values(ascending=False) * 100
missing_percent

EPEST_LOW_KG        32.006205
COMPOUND             0.000000
YEAR                 0.000000
STATE_FIPS_CODE      0.000000
COUNTY_FIPS_CODE     0.000000
EPEST_HIGH_KG        0.000000
dtype: float64

In [27]:
missing_percent = matching.isna().mean().sort_values(ascending=False) * 100
missing_percent

CASRN         8.705357
CAS Number    8.705357
COMPOUND      0.000000
dtype: float64

# Data Cleaning

### Cleaning Columns

In [54]:
#EPA
EPA_Dataset = EPA_Dataset.loc[:,['CAS Number', 'Chemical Name','Species Group', 'Exposure Type', 'Conc 1 Mean (Author)', 'Effect', 'Effect Measurement', 'Observed Response Mean']]

In [ ]:
#epest
epest = epest.loc[:,['COMPOUND', 'YEAR', 'STATE_FIPS_CODE', 'COUNTY_FIPS_CODE', 'EPEST_HIGH_KG']]

In [ ]:
#matching
matching = matching.loc[:,['COMPOUND', 'CAS Number']]

### Handling NA Values

### Fixing Column Types

In [ ]:
#EPA dataset 
EPA_Dataset.dtypes

CAS Number                int64
Chemical Name               str
Species Group               str
Exposure Type               str
Conc 1 Mean (Author)        str
Effect                      str
Effect Measurement          str
Observed Response Mean      str
dtype: object

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')