## Table of Contents
1. [Data Loading](#data-loading)
2. [Data Exploration](#data-exploration)

## Data Loading

In [2]:
#packages 
from pathlib import Path
import pandas as pd

In [3]:
# paths 
project_fldr = Path.cwd().parent
raw_fldr = project_fldr /'Data'/'unprocessed' 
processed_fldr = project_fldr /'Data'/'processed'

In [4]:
# Importing the dataframe 
EPA_Metals = (
    pd.read_csv(
        raw_fldr/'712ProjectDataCSV.csv')
)

# Data Exploration

In [5]:
EPA_Metals.shape

(620, 23)

In [6]:
EPA_Metals.head()

,CAS Number,Chemical Name,Species Scientific Name,Species Common Name,Species Group,Exposure Type,Media Type,Conc 1 Type (Standardized),Conc 1 Mean Op (Standardized),Conc 1 Mean (Standardized),...,Conc 1 Max (Standardized),Conc 1 Units (Standardized),Effect,Author,Reference Number,Title,Source,Publication Year,Citation,Summary of Additional Parameters
0,62384,(Acetato-kappaO)phenylmercury,Chlorella pyrenoidosa,Green Algae,Algae,Static,Fresh water,Total,NaN,3.0,...,NaN,AI mg/L,Mortality,"Fitzgerald,G.P., and S.L. Faust",8064,Bioassay for Algicidal vs. Algistatic Chemicals,Water Sewage Works:296-298,1963,"Fitzgerald,G.P., and S.L. Faust (1963). Bioass...",Conc 2 (Standardized): NR (NR - NR) NR | Conc...
1,62384,(Acetato-kappaO)phenylmercury,Chlorella pyrenoidosa,Green Algae,Algae,Static,Fresh water,Total,NaN,3.0,...,NaN,AI mg/L,Mortality,"Fitzgerald,G.P., and S.L. Faust",8064,Bioassay for Algicidal vs. Algistatic Chemicals,Water Sewage Works:296-298,1963,"Fitzgerald,G.P., and S.L. Faust (1963). Bioass...",Conc 2 (Standardized): NR (NR - NR) NR | Conc...
2,62384,(Acetato-kappaO)phenylmercury,Chlorella pyrenoidosa,Green Algae,Algae,Static,Fresh water,Total,NaN,3.0,...,NaN,AI mg/L,Mortality,"Fitzgerald,G.P., and S.L. Faust",8064,Bioassay for Algicidal vs. Algistatic Chemicals,Water Sewage Works:296-298,1963,"Fitzgerald,G.P., and S.L. Faust (1963). Bioass...",Conc 2 (Standardized): NR (NR - NR) NR | Conc...
3,62384,(Acetato-kappaO)phenylmercury,Chlorella pyrenoidosa,Green Algae,Algae,Static,Fresh water,Total,NaN,3.0,...,NaN,AI mg/L,Mortality,"Fitzgerald,G.P., and S.L. Faust",8064,Bioassay for Algicidal vs. Algistatic Chemicals,Water Sewage Works:296-298,1963,"Fitzgerald,G.P., and S.L. Faust (1963). Bioass...",Conc 2 (Standardized): NR (NR - NR) NR | Conc...
4,62384,(Acetato-kappaO)phenylmercury,Chlorella pyrenoidosa,Green Algae,Algae,Static,Fresh water,Total,NaN,3.0,...,NaN,AI mg/L,Mortality,"Fitzgerald,G.P., and S.L. Faust",8064,Bioassay for Algicidal vs. Algistatic Chemicals,Water Sewage Works:296-298,1963,"Fitzgerald,G.P., and S.L. Faust (1963). Bioass...",Conc 2 (Standardized): NR (NR - NR) NR | Conc...

In [7]:
EPA_Metals.info()

<class 'pandas.DataFrame'>
RangeIndex: 620 entries, 0 to 619
Data columns (total 23 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   CAS Number                        620 non-null    int64
 1   Chemical Name                     620 non-null    str
 2   Species Scientific Name           620 non-null    str
 3   Species Common Name               620 non-null    str
 4   Species Group                     620 non-null    str
 5   Exposure Type                     620 non-null    str
 6   Media Type                        620 non-null    str
 7   Conc 1 Type (Standardized)        620 non-null    str
 8   Conc 1 Mean Op (Standardized)     14 non-null     str
 9   Conc 1 Mean (Standardized)        273 non-null    float64
 10  Conc 1 Min Op (Standardized)      66 non-null     str
 11  Conc Min 1 (Standardized)         355 non-null    float64
 12  Conc 1 Max Op (Standardized)      66 non-null     str
 13  Conc 1 Max (Standardized)         355 non-null    float64
 14  Conc 1 Units (Standardized)       620 non-null    str
 15  Effect                            620 non-null    str
 16  Author                            620 non-null    str
 17  Reference Number                  620 non-null    int64
 18  Title                             620 non-null    str
 19  Source                            620 non-null    str
 20  Publication Year                  620 non-null    int64
 21  Citation                          620 non-null    str
 22  Summary of Additional Parameters  620 non-null    str
dtypes: float64(3), int64(3), str(17)
memory usage: 111.5 KB

In [8]:
EPA_Metals.describe()

,CAS Number,Conc 1 Mean (Standardized),Conc Min 1 (Standardized),Conc 1 Max (Standardized),Reference Number,Publication Year
count,6.200000e+02,273.000000,355.000000,355.000000,620.000000,620.000000
mean,7.588389e+06,456.414352,55.785171,304.315360,28737.996774,1982.691935
std,4.145029e+06,4924.656556,972.750178,4862.429934,41893.604671,11.300432
min,6.238400e+04,0.010000,0.000000,0.004000,2254.000000,1952.000000
25%,7.758954e+06,0.380000,3.200000,32.000000,9216.000000,1978.000000
50%,7.758987e+06,3.000000,3.200000,32.000000,14456.000000,1982.000000
75%,1.009975e+07,29.000000,3.200000,100.000000,15299.000000,1982.000000
max,7.608078e+07,64395.120000,18331.600000,91658.000000,193094.000000,2022.000000

In [9]:
EPA_Metals.dtypes

CAS Number                            int64
Chemical Name                           str
Species Scientific Name                 str
Species Common Name                     str
Species Group                           str
Exposure Type                           str
Media Type                              str
Conc 1 Type (Standardized)              str
Conc 1 Mean Op (Standardized)           str
Conc 1 Mean (Standardized)          float64
Conc 1 Min Op (Standardized)            str
Conc Min 1 (Standardized)           float64
Conc 1 Max Op (Standardized)            str
Conc 1 Max (Standardized)           float64
Conc 1 Units (Standardized)             str
Effect                                  str
Author                                  str
Reference Number                      int64
Title                                   str
Source                                  str
Publication Year                      int64
Citation                                str
Summary of Additional Parameters        str
dtype: object

In [10]:
missing_percent = EPA_Metals.isna().mean().sort_values(ascending=False) * 100
missing_percent

Conc 1 Mean Op (Standardized)       97.741935
Conc 1 Min Op (Standardized)        89.354839
Conc 1 Max Op (Standardized)        89.354839
Conc 1 Mean (Standardized)          55.967742
Conc 1 Max (Standardized)           42.741935
Conc Min 1 (Standardized)           42.741935
CAS Number                           0.000000
Media Type                           0.000000
Exposure Type                        0.000000
Species Group                        0.000000
Species Common Name                  0.000000
Species Scientific Name              0.000000
Chemical Name                        0.000000
Conc 1 Type (Standardized)           0.000000
Conc 1 Units (Standardized)          0.000000
Effect                               0.000000
Author                               0.000000
Reference Number                     0.000000
Title                                0.000000
Source                               0.000000
Publication Year                     0.000000
Citation                             0.000000
Summary of Additional Parameters     0.000000
dtype: float64